version: "3.8"
services:
  build-wasm:
    image: bpffilter
    build: .
    user: "${USER_ID}:${GROUP_ID}"
    volumes:
      - type: bind
        source: ./
        target: /home/ubuntu/project
      - type: bind
        source: ./build-docker
        target: /home/ubuntu/project/build
